### ISSUE TITLE
testing jump to type definition: nil:unexpected EOF while parsing

### ISSUE THREAD

**Issue by jgarte** [fischerling/vis-lspc#24]
```
10:20 nil:unexpected EOF while parsing
```

I was testing with [python-lsp-server](https://github.com/python-lsp/python-lsp-server) and `< D> - jump to type definition`.

```
LSPC Sending: Content-Length: 181

{"id":0, "method":"initialize", "jsonrpc":"2.0", "params":{"client":{"version":"0.1.3", "name":"vis-lspc"}, "processID":24510, "capabilities":{"workspace":{"configuration":false}}}}
LS response(STDOUT): Content-Length: 777
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","id":0,"result":{"capabilities":{"codeActionProvider":true,"codeLensProvider":{"resolveProvider":false},"completionProvider":{"resolveProvider":true,"triggerCharacters":["."]},"documentFormattingProvider":true,"documentHighlightProvider":true,"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"definitionProvider":true,"executeCommandProvider":{"commands":[]},"hoverProvider":true,"referencesProvider":true,"renameProvider":true,"foldingRangeProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",",","="]},"textDocumentSync":{"change":2,"save":{"includeText":true},"openClose":true},"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}},"experimental":{}},"serverInfo":{"name":"pylsp","version":"1.2.4"}}}
LSPC Sending: Content-Length: 41

{"jsonrpc":"2.0", "method":"initialized"}
LSPC Sending: Content-Length: 414

{"params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py", "version":0, "languageId":"python", "text":"import bibtexparser\n\nwith open('bibtex.bib') as bibtex_file:\n    bib_database = bibtexparser.load(bibtex_file)\n\n#print(bib_database.entries)\n#print(bib_database.comments)\n#print(bib_database.preambles)\nprint(bib_database.st\n"}}, "method":"textDocument\/didOpen", "jsonrpc":"2.0"}
send didChange
LSPC Sending: Content-Length: 414

{"params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py", "version":1}, "contentChanges":[{"text":"import bibtexparser\n\nwith open('bibtex.bib') as bibtex_file:\n    bib_database = bibtexparser.load(bibtex_file)\n\n#print(bib_database.entries)\n#print(bib_database.comments)\n#print(bib_database.preambles)\nprint(bib_database.st\n"}]}, "method":"textDocument\/didChange", "jsonrpc":"2.0"}
LSPC Sending: Content-Length: 184

{"id":1, "method":"textDocument\/completion", "jsonrpc":"2.0", "params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py"}, "position":{"line":8, "character":21}}}
LS response(STDOUT): Content-Length: 1022
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"textDocument\/publishDiagnostics","params":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py","diagnostics":[{"source":"pyflakes","range":{"start":{"line":8,"character":22},"end":{"line":8,"character":44}},"message":"unexpected EOF while parsing","severity":1},{"source":"pycodestyle","range":{"start":{"line":5,"character":0},"end":{"line":5,"character":29}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":6,"character":0},"end":{"line":6,"character":30}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":7,"character":0},"end":{"line":7,"character":31}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":9,"character":0},"end":{"line":9,"character":100}},"message
LS response(STDOUT): ":"E901 TokenError: EOF in multi-line statement","code":"E901","severity":2}]}}
remember diagnostics for /home/jgart/bibtexparser/read.py
LS response(STDOUT): Content-Length: 67
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","id":1,"result":{"isIncomplete":false,"items":[]}}
send didChange
LSPC Sending: Content-Length: 414

{"params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py", "version":2}, "contentChanges":[{"text":"import bibtexparser\n\nwith open('bibtex.bib') as bibtex_file:\n    bib_database = bibtexparser.load(bibtex_file)\n\n#print(bib_database.entries)\n#print(bib_database.comments)\n#print(bib_database.preambles)\nprint(bib_database.st\n"}]}, "method":"textDocument\/didChange", "jsonrpc":"2.0"}
LSPC Sending: Content-Length: 184

{"id":2, "method":"textDocument\/completion", "jsonrpc":"2.0", "params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py"}, "position":{"line":8, "character":21}}}
LS response(STDOUT): Content-Length: 67
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","id":2,"result":{"isIncomplete":false,"items":[]}}
LS response(STDOUT): Content-Length: 1022
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"textDocument\/publishDiagnostics","params":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py","diagnostics":[{"source":"pyflakes","range":{"start":{"line":8,"character":22},"end":{"line":8,"character":44}},"message":"unexpected EOF while parsing","severity":1},{"source":"pycodestyle","range":{"start":{"line":5,"character":0},"end":{"line":5,"character":29}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":6,"character":0},"end":{"line":6,"character":30}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":7,"character":0},"end":{"line":7,"character":31}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":9,"character":0},"end":{"line":9,"character":100}},"message
LS response(STDOUT): ":"E901 TokenError: EOF in multi-line statement","code":"E901","severity":2}]}}
remember diagnostics for /home/jgart/bibtexparser/read.py
send didChange
LSPC Sending: Content-Length: 440

{"params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py", "version":3}, "contentChanges":[{"text":"import bibtexparser\nimport random\n\nwith open('bibtex.bib') as bibtex_file:\n    bib_database = bibtexparser.load(bibtex_file)\n\n#print(bib_database.entries)\n#print(bib_database.comments)\n#print(bib_database.preambles)\n#print(bib_database.st\nrandom.s\n"}]}, "method":"textDocument\/didChange", "jsonrpc":"2.0"}
LSPC Sending: Content-Length: 184

{"id":3, "method":"textDocument\/completion", "jsonrpc":"2.0", "params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py"}, "position":{"line":10, "character":8}}}
LS response(STDOUT): Content-Length: 866
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"textDocument\/publishDiagnostics","params":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py","diagnostics":[{"source":"pycodestyle","range":{"start":{"line":6,"character":0},"end":{"line":6,"character":29}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":7,"character":0},"end":{"line":7,"character":30}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":8,"character":0},"end":{"line":8,"character":31}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":9,"character":0},"end":{"line":9,"character":23}},"message":"E265 block comment should start with '# '","code":"E265","severity":2}]}}
remember diagnostics for /home/jgart/bibtexparser/read.py
LS response(STDOUT): Content-Length: 981
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","id":3,"result":{"isIncomplete":false,"items":[{"label":"sample(population, k)","kind":3,"sortText":"asample","insertText":"sample","data":{"doc_uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py"}},{"label":"seed(a, version)","kind":3,"sortText":"aseed","insertText":"seed","data":{"doc_uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py"}},{"label":"setstate(state)","kind":3,"sortText":"asetstate","insertText":"setstate","data":{"doc_uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py"}},{"label":"SG_MAGICCONST","kind":6,"sortText":"aSG_MAGICCONST","insertText":"SG_MAGICCONST","data":{"doc_uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py"}},{"label":"shuffle(x, random)","kind":3,"sortText":"ashuffle","insertText":"shuffle","data":{"doc_uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py"}},{"label":"SystemRandom","kind":7,"sortText":"aSystemRandom","insertText":"SystemRandom","data":{"doc_uri":"file:\/\/\/hom
LS response(STDOUT): e\/jgart\/bibtexparser\/read.py"}}]}}
collect choice using: printf "sample(population, k)
seed(a, version)
setstate(state)
SG_MAGICCONST
shuffle(x, random)
SystemRandom
" | sk
Completion old_pos=247, old_range={start=247, finish=248}, old_word=\n
Cursor looks like its not on the completion token
replace the token: s  we found being a prefix of the completion
send didChange
LSPC Sending: Content-Length: 428

{"params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py", "version":4}, "contentChanges":[{"text":"import bibtexparser\nimport random\n\nwith open('bibtex.bib') as bibtex_file:\n    bib_database = bibtexparser.load(bibtex_file)\n\n#print(bib_database.entries)\n#print(bib_database.comments)\n#print(bib_database.preambles)\nprint(bib_database.e\n"}]}, "method":"textDocument\/didChange", "jsonrpc":"2.0"}
LSPC Sending: Content-Length: 184

{"id":4, "method":"textDocument\/completion", "jsonrpc":"2.0", "params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py"}, "position":{"line":9, "character":20}}}
LS response(STDOUT): Content-Length: 67
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","id":4,"result":{"isIncomplete":false,"items":[]}}
LS response(STDOUT): Content-Length: 1024
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"textDocument\/publishDiagnostics","params":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py","diagnostics":[{"source":"pyflakes","range":{"start":{"line":9,"character":21},"end":{"line":9,"character":42}},"message":"unexpected EOF while parsing","severity":1},{"source":"pycodestyle","range":{"start":{"line":6,"character":0},"end":{"line":6,"character":29}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":7,"character":0},"end":{"line":7,"character":30}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":8,"character":0},"end":{"line":8,"character":31}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":10,"character":0},"end":{"line":10,"character":100}},"messa
LS response(STDOUT): ge":"E901 TokenError: EOF in multi-line statement","code":"E901","severity":2}]}}
remember diagnostics for /home/jgart/bibtexparser/read.py
send didChange
LSPC Sending: Content-Length: 428

{"params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py", "version":5}, "contentChanges":[{"text":"import bibtexparser\nimport random\n\nwith open('bibtex.bib') as bibtex_file:\n    bib_database = bibtexparser.load(bibtex_file)\n\n#print(bib_database.entries)\n#print(bib_database.comments)\n#print(bib_database.preambles)\nprint(bib_database.e\n"}]}, "method":"textDocument\/didChange", "jsonrpc":"2.0"}
LSPC Sending: Content-Length: 184

{"id":5, "method":"textDocument\/completion", "jsonrpc":"2.0", "params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py"}, "position":{"line":9, "character":20}}}
LS response(STDOUT): Content-Length: 67
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","id":5,"result":{"isIncomplete":false,"items":[]}}
LS response(STDOUT): Content-Length: 1024
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"textDocument\/publishDiagnostics","params":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py","diagnostics":[{"source":"pyflakes","range":{"start":{"line":9,"character":21},"end":{"line":9,"character":42}},"message":"unexpected EOF while parsing","severity":1},{"source":"pycodestyle","range":{"start":{"line":6,"character":0},"end":{"line":6,"character":29}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":7,"character":0},"end":{"line":7,"character":30}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":8,"character":0},"end":{"line":8,"character":31}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":10,"character":0},"end":{"line":10,"character":100}},"messa
LS response(STDOUT): ge":"E901 TokenError: EOF in multi-line statement","code":"E901","severity":2}]}}
remember diagnostics for /home/jgart/bibtexparser/read.py
send didChange
LSPC Sending: Content-Length: 426

{"params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py", "version":6}, "contentChanges":[{"text":"import bibtexparser\nimport random\n\nwith open('bibtex.bib') as bibtex_file:\n    bib_database = bibtexparser.load(bibtex_file)\n\n#print(bib_database.entries)\n#print(bib_database.comments)\n#print(bib_database.preambles)\nprint(bib_database\n"}]}, "method":"textDocument\/didChange", "jsonrpc":"2.0"}
LSPC Sending: Content-Length: 184

{"id":6, "method":"textDocument\/references", "jsonrpc":"2.0", "params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py"}, "position":{"line":9, "character":16}}}
LS response(STDOUT): Content-Length: 1087
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","id":6,"error":{"code":-32602,"message":"TypeError: 'NoneType' object is not subscriptable","data":{"traceback":["  File \"\/nix\/store\/s929vczw40xgcc9rj3rwckganpg62gw8-python3.8-python-lsp-jsonrpc-1.0.0\/lib\/python3.8\/site-packages\/pylsp_jsonrpc\/endpoint.py\", line 116, in consume\n    self._handle_request(message['id'], message['method'], message.get('params'))\n","  File \"\/nix\/store\/s929vczw40xgcc9rj3rwckganpg62gw8-python3.8-python-lsp-jsonrpc-1.0.0\/lib\/python3.8\/site-packages\/pylsp_jsonrpc\/endpoint.py\", line 185, in _handle_request\n    handler_result = handler(params)\n","  File \"\/nix\/store\/s929vczw40xgcc9rj3rwckganpg62gw8-python3.8-python-lsp-jsonrpc-1.0.0\/lib\/python3.8\/site-packages\/pylsp_jsonrpc\/dispatchers.py\", line 25, in handler\n    return method(**(params or {}))\n","  File \"\/nix\/store\/9giqbyz5mr8zc3c9ka2n3v95s60v66iq-python3.8-python-lsp-server-1.2.4\/lib\/python3.8\/sit
LS response(STDERR): 2021-11-30 18:31:45,897 EST - ERROR - pylsp_jsonrpc.endpoint - Failed to handle request 6
Traceback (most recent call last):
  File "/nix/store/s929vczw40xgcc9rj3rwckganpg62gw8-python3.8-python-lsp-jsonrpc-1.0.0/lib/python3.8/site-packages/pylsp_jsonrpc/endpoint.py", line 116, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/nix/store/s929vczw40xgcc9rj3rwckganpg62gw8-python3.8-python-lsp-jsonrpc-1.0.0/lib/python3.8/site-packages/pylsp_jsonrpc/endpoint.py", line 185, in _handle_request
    handler_result = handler(params)
  File "/nix/store/s929vczw40xgcc9rj3rwckganpg62gw8-python3.8-python-lsp-jsonrpc-1.0.0/lib/python3.8/site-packages/pylsp_jsonrpc/dispatchers.py", line 25, in handler
    return method(**(params or {}))
  File "/nix/store/9giqbyz5mr8zc3c9ka2n3v95s60v66iq-python3.8-python-lsp-server-1.2.4/lib/python3.8/site-packages/pylsp/python_lsp.py", line 379, in m_text_document__references
    exclude_declaration = not context['includeDeclaration']
Type
LS response(STDOUT): e-packages\/pylsp\/python_lsp.py\", line 379, in m_text_document__references\n    exclude_declaration = not context['includeDeclaration']\n"]}}}
LSPC Error: TypeError: 'NoneType' object is not subscriptable (-32602) occurred during textDocument/references
LS response(STDERR): Error: 'NoneType' object is not subscriptable

LS response(STDOUT): Content-Length: 1024
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"textDocument\/publishDiagnostics","params":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py","diagnostics":[{"source":"pyflakes","range":{"start":{"line":9,"character":19},"end":{"line":9,"character":38}},"message":"unexpected EOF while parsing","severity":1},{"source":"pycodestyle","range":{"start":{"line":6,"character":0},"end":{"line":6,"character":29}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":7,"character":0},"end":{"line":7,"character":30}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":8,"character":0},"end":{"line":8,"character":31}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":10,"character":0},"end":{"line":10,"character":100}},"messa
LS response(STDOUT): ge":"E901 TokenError: EOF in multi-line statement","code":"E901","severity":2}]}}
remember diagnostics for /home/jgart/bibtexparser/read.py
LSPC Error: language server python does not provide implementation
send didChange
LSPC Sending: Content-Length: 426

{"params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py", "version":7}, "contentChanges":[{"text":"import bibtexparser\nimport random\n\nwith open('bibtex.bib') as bibtex_file:\n    bib_database = bibtexparser.load(bibtex_file)\n\n#print(bib_database.entries)\n#print(bib_database.comments)\n#print(bib_database.preambles)\nprint(bib_database\n"}]}, "method":"textDocument\/didChange", "jsonrpc":"2.0"}
LSPC Sending: Content-Length: 184

{"id":7, "method":"textDocument\/definition", "jsonrpc":"2.0", "params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py"}, "position":{"line":9, "character":15}}}
LS response(STDOUT): Content-Length: 166
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","id":7,"result":[{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py","range":{"start":{"line":4,"character":4},"end":{"line":4,"character":16}}}]}
Handle location: {"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py", "range":{"end":{"line":4, "character":16}, "start":{"line":4, "character":4}}}
LS response(STDOUT): Content-Length: 1024
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"textDocument\/publishDiagnostics","params":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py","diagnostics":[{"source":"pyflakes","range":{"start":{"line":9,"character":19},"end":{"line":9,"character":38}},"message":"unexpected EOF while parsing","severity":1},{"source":"pycodestyle","range":{"start":{"line":6,"character":0},"end":{"line":6,"character":29}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":7,"character":0},"end":{"line":7,"character":30}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":8,"character":0},"end":{"line":8,"character":31}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":10,"character":0},"end":{"line":10,"character":100}},"messa
LS response(STDOUT): ge":"E901 TokenError: EOF in multi-line statement","code":"E901","severity":2}]}}
remember diagnostics for /home/jgart/bibtexparser/read.py
send didChange
LSPC Sending: Content-Length: 426

{"params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py", "version":8}, "contentChanges":[{"text":"import bibtexparser\nimport random\n\nwith open('bibtex.bib') as bibtex_file:\n    bib_database = bibtexparser.load(bibtex_file)\n\n#print(bib_database.entries)\n#print(bib_database.comments)\n#print(bib_database.preambles)\nprint(bib_database\n"}]}, "method":"textDocument\/didChange", "jsonrpc":"2.0"}
LSPC Sending: Content-Length: 183

{"id":8, "method":"textDocument\/definition", "jsonrpc":"2.0", "params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py"}, "position":{"line":9, "character":7}}}
LS response(STDOUT): Content-Length: 166
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","id":8,"result":[{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py","range":{"start":{"line":4,"character":4},"end":{"line":4,"character":16}}}]}
Handle location: {"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py", "range":{"end":{"line":4, "character":16}, "start":{"line":4, "character":4}}}
LS response(STDOUT): Content-Length: 1024
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"textDocument\/publishDiagnostics","params":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py","diagnostics":[{"source":"pyflakes","range":{"start":{"line":9,"character":19},"end":{"line":9,"character":38}},"message":"unexpected EOF while parsing","severity":1},{"source":"pycodestyle","range":{"start":{"line":6,"character":0},"end":{"line":6,"character":29}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":7,"character":0},"end":{"line":7,"character":30}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":8,"character":0},"end":{"line":8,"character":31}},"message":"E265 block comment should start with '# '","code":"E265","severity":2},{"source":"pycodestyle","range":{"start":{"line":10,"character":0},"end":{"line":10,"character":100}},"messa
LS response(STDOUT): ge":"E901 TokenError: EOF in multi-line statement","code":"E901","severity":2}]}}
remember diagnostics for /home/jgart/bibtexparser/read.py
LSPC Error: language server python does not provide typeDefinition
Show diagnostics for 10
LSPC Sending: Content-Length: 134

{"params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py"}}, "method":"textDocument\/didSave", "jsonrpc":"2.0"}
LSPC Sending: Content-Length: 135

{"params":{"textDocument":{"uri":"file:\/\/\/home\/jgart\/bibtexparser\/read.py"}}, "method":"textDocument\/didClose", "jsonrpc":"2.0"}

```

**Comment by fischerling** [comment]
> ```
> 10:20 nil:unexpected EOF while parsing
> ```

Was this the message printed by vis-lspc? Because I can not find this string in the log you provided.

> I was testing with [python-lsp-server](https://github.com/python-lsp/python-lsp-server) and `< D> - jump to type definition`.
TypeDefinitions are not supported by the Language Server

> ```{"jsonrpc":"2.0","id":0,"result":{"capabilities":{"codeActionProvider":true,"codeLensProvider":{"resolveProvider":false},"completionProvider":{"resolveProvider":true,"triggerCharacters":["."]},"documentFormattingProvider":true,"documentHighlightProvider":true,"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"definitionProvider":true,"executeCommandProvider":{"commands":[]},"hoverProvider":true,"referencesProvider":true,"renameProvider":true,"foldingRangeProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",",","="]},"textDocumentSync":{"change":2,"save":{"includeText":true},"openClose":true},"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}},"experimental":{}},"serverInfo":{"name":"pylsp","version":"1.2.4"}}}```
Those are the reported capabilities from the server and there is no `typeDefinitionProvider` only a `definitionProvider`.

**Comment by jgarte** [comment]
> > ```
> > 10:20 nil:unexpected EOF while parsing
> > ```
> 
> Was this the message printed by vis-lspc? Because I can not find this string in the log you provided.
> 
> > I was testing with [python-lsp-server](https://github.com/python-lsp/python-lsp-server) and `< D> - jump to type definition`.
> > TypeDefinitions are not supported by the Language Server
> 
> > `{"jsonrpc":"2.0","id":0,"result":{"capabilities":{"codeActionProvider":true,"codeLensProvider":{"resolveProvider":false},"completionProvider":{"resolveProvider":true,"triggerCharacters":["."]},"documentFormattingProvider":true,"documentHighlightProvider":true,"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"definitionProvider":true,"executeCommandProvider":{"commands":[]},"hoverProvider":true,"referencesProvider":true,"renameProvider":true,"foldingRangeProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",",","="]},"textDocumentSync":{"change":2,"save":{"includeText":true},"openClose":true},"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}},"experimental":{}},"serverInfo":{"name":"pylsp","version":"1.2.4"}}}`
> > Those are the reported capabilities from the server and there is no `typeDefinitionProvider` only a `definitionProvider`.

No, that message was printed by vis. I think it is a lua error.

**Comment by fischerling** [comment]
But it does not look like a lua error encountered in vis. Normaly it would have the file and lin information.

Was it printed by vis:message (in a seperate message window) or vis:info (on the status line)?

The message looks like a diagnostic message generated by vis-lspc to me (<line>:<colum> <code>:<message>).

See:
https://github.com/fischerling/vis-lspc/blob/b08f3bfbb0428aba83968d3339e12c7e29d7997a/init.lua#L1109-L1112

But I have no idea why vis-lspc would present you this diagnostic unasked.

**Comment by jgarte** [comment]
> vis:messag

It was printed by `vis:message` in a separate message window.

**Comment by fischerling** [comment]
Yea it is for sure a diagnostic generated by the language server.
In your log one of the last lines is
> Show diagnostics for 10

So maybe you hit `gr` unwillingly.

**Comment by jgarte** [comment]
> Yea it is for sure a diagnostic generated by the language server. In your log one of the last lines is
> 
> > Show diagnostics for 10
> 
> So maybe you hit `gr` unwillingly.

That's definitely possible

**Comment by fischerling** [comment]
> > Yea it is for sure a diagnostic generated by the language server. In your log one of the last lines is
> > > Show diagnostics for 10
> > 
> > 
> > So maybe you hit `gr` unwillingly.
> 
> That's definitely possible

So should we close this?

**Comment by jgarte** [comment]
I'm closing
